import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  Patch,
  Post,
  Put,
  UseGuards,
} from "@nestjs/common";
import { AuthGuard } from "../common/guards/auth.guard";
import { OrgGuard } from "../common/guards/org.guard";
import { CurrentOrg } from "../common/decorators/current-org";
import { EnvVarsService } from "./env-vars.service";

@Controller("api/projects/:projectId/environments/:envId/env-vars")
@UseGuards(AuthGuard, OrgGuard)
export class EnvVarsController {
  constructor(private readonly envVars: EnvVarsService) {}

  @Get()
  list(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
  ) {
    return this.envVars.list(orgId, projectId, envId);
  }

  @Post()
  create(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Body() body: { service: string; key: string; value: string; isAutoGenerated?: boolean },
  ) {
    return this.envVars.create(orgId, projectId, envId, body);
  }

  @Patch(":varId")
  update(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Param("varId") varId: string,
    @Body() body: { value?: string; key?: string },
  ) {
    return this.envVars.update(orgId, projectId, envId, varId, body);
  }

  @Delete(":varId")
  remove(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Param("varId") varId: string,
  ) {
    return this.envVars.delete(orgId, projectId, envId, varId);
  }

  @Put("bulk")
  bulk(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Body() body: { vars: Array<{ service: string; key: string; value: string; isAutoGenerated?: boolean }> },
  ) {
    return this.envVars.bulkUpsert(orgId, projectId, envId, body.vars);
  }
}
