import { Injectable, Inject, NotFoundException, BadRequestException } from "@nestjs/common";
import type { PrismaClient } from "@heizen/db";
import { PRISMA } from "../prisma/prisma.module";
import { EnvironmentsService } from "../environments/environments.service";
import { EncryptionService } from "../common/services/encryption.service";
import { AuditLogService } from "../audit/audit.service";

@Injectable()
export class EnvVarsService {
  constructor(
    @Inject(PRISMA) private readonly prisma: PrismaClient,
    private readonly environments: EnvironmentsService,
    private readonly encryption: EncryptionService,
    private readonly audit: AuditLogService,
  ) {}

  async list(orgId: string, projectId: string, envId: string) {
    await this.environments.get(orgId, projectId, envId);
    const vars = await this.prisma.envVariable.findMany({
      where: { environmentId: envId },
      select: {
        id: true,
        service: true,
        key: true,
        isAutoGenerated: true,
        dismissed: true,
        value: true,
      },
    });

    return vars.map((v) => ({
      id: v.id,
      service: v.service,
      key: v.key,
      isAutoGenerated: v.isAutoGenerated,
      dismissed: v.dismissed,
      hasValue: v.value.length > 0,
    }));
  }

  async create(
    orgId: string,
    projectId: string,
    envId: string,
    data: { service: string; key: string; value: string; isAutoGenerated?: boolean },
  ) {
    await this.environments.get(orgId, projectId, envId);
    return this.prisma.envVariable.create({
      data: {
        environmentId: envId,
        service: data.service,
        key: data.key,
        value: this.encryption.encrypt(data.value),
        isAutoGenerated: data.isAutoGenerated ?? false,
      },
      select: { id: true, service: true, key: true, isAutoGenerated: true, value: true },
    }).then((v) => ({ id: v.id, service: v.service, key: v.key, isAutoGenerated: v.isAutoGenerated, hasValue: true }));
  }

  async update(
    orgId: string,
    projectId: string,
    envId: string,
    varId: string,
    data: { value?: string; key?: string },
  ) {
    await this.environments.get(orgId, projectId, envId);
    const existing = await this.prisma.envVariable.findFirst({
      where: { id: varId, environmentId: envId },
    });
    if (!existing) throw new NotFoundException("Env var not found");

    return this.prisma.envVariable.update({
      where: { id: varId },
      data: {
        key: data.key,
        value: data.value ? this.encryption.encrypt(data.value) : undefined,
      },
      select: { id: true, service: true, key: true, isAutoGenerated: true },
    }).then((v) => ({ ...v, hasValue: true }));
  }

  async delete(orgId: string, projectId: string, envId: string, varId: string) {
    await this.environments.get(orgId, projectId, envId);
    return this.prisma.envVariable.delete({ where: { id: varId } });
  }

  async dismiss(
    orgId: string,
    projectId: string,
    envId: string,
    varId: string,
  ) {
    await this.environments.get(orgId, projectId, envId);
    const existing = await this.prisma.envVariable.findFirst({
      where: { id: varId, environmentId: envId },
    });
    if (!existing) throw new NotFoundException("Env var not found");
    return this.prisma.envVariable.update({
      where: { id: varId },
      data: { dismissed: true },
    });
  }

  async bulkUpsert(
    orgId: string,
    projectId: string,
    envId: string,
    vars: Array<{ service: string; key: string; value: string; isAutoGenerated?: boolean }>,
  ) {
    await this.environments.get(orgId, projectId, envId);

    for (const v of vars) {
      await this.prisma.envVariable.upsert({
        where: {
          environmentId_service_key: {
            environmentId: envId,
            service: v.service,
            key: v.key,
          },
        },
        create: {
          environmentId: envId,
          service: v.service,
          key: v.key,
          value: this.encryption.encrypt(v.value),
          isAutoGenerated: v.isAutoGenerated ?? false,
        },
        update: {
          value: this.encryption.encrypt(v.value),
          isAutoGenerated: v.isAutoGenerated,
        },
      });
    }

    return this.list(orgId, projectId, envId);
  }

  async listRaw(orgId: string, projectId: string, envId: string) {
    await this.environments.get(orgId, projectId, envId);
    const vars = await this.prisma.envVariable.findMany({
      where: {
        environmentId: envId,
        service: "shared",
        isAutoGenerated: false,
      },
      select: { key: true, value: true },
      orderBy: { key: "asc" },
    });
    return vars.map((v) => ({
      key: v.key,
      value: v.value ? this.encryption.decrypt(v.value) : "",
    }));
  }

  async replaceRaw(
    orgId: string,
    projectId: string,
    envId: string,
    content: string,
    actorId?: string | null,
  ) {
    await this.environments.get(orgId, projectId, envId);

    const { parseDotenv } = await import("@heizen/shared");
    const parsed = parseDotenv(content);
    if (parsed.errors.length > 0) {
      throw new BadRequestException({
        message: "Parse error",
        errors: parsed.errors,
      });
    }

    await this.prisma.$transaction(async (tx) => {
      await tx.envVariable.deleteMany({
        where: {
          environmentId: envId,
          service: "shared",
          isAutoGenerated: false,
        },
      });

      if (parsed.entries.length > 0) {
        await tx.envVariable.createMany({
          data: parsed.entries.map((entry) => ({
            environmentId: envId,
            service: "shared",
            key: entry.key,
            value: this.encryption.encrypt(entry.value),
            isAutoGenerated: false,
          })),
        });
      }

      await this.audit.logInTx(tx, {
        actorId: actorId ?? null,
        action: "ENV_VARS_REPLACED",
        resourceType: "ENVIRONMENT",
        resourceId: envId,
        metadata: { count: parsed.entries.length, projectId },
      });
    });

    return {
      count: parsed.entries.length,
      warnings: parsed.warnings,
    };
  }

  async getDecryptedForDeployment(envId: string): Promise<Record<string, Record<string, string>>> {
    const vars = await this.prisma.envVariable.findMany({
      where: { environmentId: envId },
    });

    const result: Record<string, Record<string, string>> = { shared: {} };

    for (const v of vars) {
      if (!v.value) continue;
      const service = v.service === "shared" ? "shared" : v.service;
      if (!result[service]) result[service] = {};
      try {
        result[service]![v.key] = this.encryption.decrypt(v.value);
      } catch {
        // skip invalid
      }
    }

    return result;
  }
}
