import {
  Body,
  Controller,
  Delete,
  Get,
  Param,
  Patch,
  Post,
  Put,
  UseGuards,
} from "@nestjs/common";
import { AuthGuard } from "../common/guards/auth.guard";
import { OrgGuard } from "../common/guards/org.guard";
import {
  ProjectRoleGuard,
  RequireProjectRole,
} from "../common/rbac";
import { CurrentOrg } from "../common/decorators/current-org";
import { CurrentUser } from "../common/decorators/current-user";
import { EnvVarsService } from "./env-vars.service";

@Controller("api/projects/:projectId/environments/:envId/env-vars")
@UseGuards(AuthGuard, OrgGuard, ProjectRoleGuard)
export class EnvVarsController {
  constructor(private readonly envVars: EnvVarsService) {}

  @Get()
  list(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
  ) {
    return this.envVars.list(orgId, projectId, envId);
  }

  // Raw secrets (decrypted) — DEPLOYER/OWNER. Viewers see the keys
  // via the regular /list, not the values.
  @Get("raw")
  @RequireProjectRole("OWNER", "DEPLOYER")
  listRaw(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
  ) {
    return this.envVars.listRaw(orgId, projectId, envId);
  }

  @Put("raw")
  @RequireProjectRole("OWNER", "DEPLOYER")
  replaceRaw(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Body() body: { content: string },
    @CurrentUser() user: { id: string },
  ) {
    return this.envVars.replaceRaw(orgId, projectId, envId, body.content ?? "", user?.id ?? null);
  }

  @Post()
  @RequireProjectRole("OWNER", "DEPLOYER")
  create(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Body() body: { service: string; key: string; value: string; isAutoGenerated?: boolean },
  ) {
    return this.envVars.create(orgId, projectId, envId, body);
  }

  @Patch(":varId")
  @RequireProjectRole("OWNER", "DEPLOYER")
  update(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Param("varId") varId: string,
    @Body() body: { value?: string; key?: string },
  ) {
    return this.envVars.update(orgId, projectId, envId, varId, body);
  }

  @Delete(":varId")
  @RequireProjectRole("OWNER", "DEPLOYER")
  remove(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Param("varId") varId: string,
  ) {
    return this.envVars.delete(orgId, projectId, envId, varId);
  }

  @Patch(":varId/dismiss")
  @RequireProjectRole("OWNER", "DEPLOYER")
  dismiss(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Param("varId") varId: string,
  ) {
    return this.envVars.dismiss(orgId, projectId, envId, varId);
  }

  @Put("bulk")
  @RequireProjectRole("OWNER", "DEPLOYER")
  bulk(
    @CurrentOrg() orgId: string,
    @Param("projectId") projectId: string,
    @Param("envId") envId: string,
    @Body() body: { vars: Array<{ service: string; key: string; value: string; isAutoGenerated?: boolean }> },
  ) {
    return this.envVars.bulkUpsert(orgId, projectId, envId, body.vars);
  }
}
