"use client";

import { Suspense, useEffect, useState, useCallback } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Copy, Check, ExternalLink } from "lucide-react";
import type { HeizenConfig } from "@heizen/shared";
import { ConnectGitHub } from "@/components/github/ConnectGitHub";
import { GitHubInstallError } from "@/components/github/GitHubInstallError";
import { IndexingProgress } from "@/components/github/IndexingProgress";
import { IndexingResults } from "@/components/indexing/IndexingResults";
import { DeployForm } from "@/components/deploy/DeployForm";
import { DeployingState } from "@/components/deploy/DeployingState";
import { CostEstimator } from "@/components/deploy/CostEstimator";
import { ResourceGraph } from "@/components/resources/ResourceGraph";
import { EnvVarTable } from "@/components/env-vars/EnvVarTable";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { api } from "@/lib/api";
import { useSse } from "@/hooks/useSse";
import { useIndexingComplete, useEnvironmentStatus } from "@/hooks/useWebSocket";
import type { IndexingSsePayload } from "@heizen/shared";

interface Project {
  id: string;
  slug: string;
  githubOwner: string | null;
  githubRepo: string | null;
  githubInstallationId: string | null;
}

interface Environment {
  id: string;
  type: string;
  status: string;
  heizenConfig: HeizenConfig | null;
  lastDeployedAt: string | null;
  stackOutputs: Record<string, unknown> | null;
}

interface EnvVar {
  hasValue: boolean;
  isAutoGenerated: boolean;
  dismissed: boolean;
}

function buildDefaultHeizenConfig(
  projectSlug: string,
  envType: "staging" | "production",
): HeizenConfig {
  return {
    version: 1,
    project: projectSlug,
    env: envType,
    region: "us-east-1",
    ecr: { image: "", tag: "latest" },
    networking: { nat: "none", vpcCidr: "10.0.0.0/16" },
    loadBalancer: { enabled: false },
    services: [
      {
        name: "app",
        type: "backend",
        port: 3000,
        cpu: 256,
        memory: 512,
        scaling: { min: 1, max: 3, cpuTarget: 70 },
        command: "node dist/main.js",
        healthCheck: { path: "/health", codes: "200" },
      },
    ],
    database: { engine: "none" },
    cache: { engine: "none" },
    storage: { enabled: false },
  };
}

function CopyButton({ value }: { value: string }) {
  const [copied, setCopied] = useState(false);

  const copy = async () => {
    await navigator.clipboard.writeText(value);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Button variant="ghost" size="icon" onClick={copy} className="h-7 w-7 shrink-0">
      {copied ? <Check size={14} className="text-green-500" /> : <Copy size={14} />}
    </Button>
  );
}

export default function EnvironmentPage({
  params,
}: {
  params: Promise<{ projectSlug: string; env: string }>;
}) {
  return (
    <Suspense
      fallback={
        <div className="mx-auto max-w-5xl space-y-4 p-6">
          <Skeleton className="h-8 w-48" />
          <Skeleton className="h-32 w-full rounded-lg" />
        </div>
      }
    >
      <EnvironmentPageContent params={params} />
    </Suspense>
  );
}

function EnvironmentPageContent({
  params,
}: {
  params: Promise<{ projectSlug: string; env: string }>;
}) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const defaultTab = searchParams.get("tab") === "variables" ? "variables" : "overview";
  const [projectSlug, setProjectSlug] = useState("");
  const [envType, setEnvType] = useState<"staging" | "production">("staging");
  const [project, setProject] = useState<Project | null>(null);
  const [environment, setEnvironment] = useState<Environment | null>(null);
  const [indexing, setIndexing] = useState(false);
  const [indexingError, setIndexingError] = useState<string | null>(null);
  const [showDeployForm, setShowDeployForm] = useState(false);
  const [resources, setResources] = useState<
    Array<{ id: string; pulumiUrn: string; type: string; name: string; dependencies: string[] }>
  >([]);
  const [missingEnvCount, setMissingEnvCount] = useState(0);
  const [suggestionCount, setSuggestionCount] = useState(0);
  const [loading, setLoading] = useState(true);

  const indexStreamUrl = project
    ? `/api/projects/${project.id}/github/index/stream`
    : null;
  const { data: indexEvents, reset: resetIndexEvents } = useSse<IndexingSsePayload>(
    indexStreamUrl,
    indexing,
  );

  const load = useCallback(async (slug: string, env: string) => {
    try {
      const projects = await api<Array<Project & { environments: Environment[] }>>("/api/projects");
      const p = projects.find((pr) => pr.slug === slug);
      if (!p) {
        setLoading(false);
        return;
      }

      setProject(p);
      const envRecord = p.environments.find(
        (e) => e.type.toLowerCase() === env.toLowerCase(),
      );
      if (envRecord) {
        setEnvironment(envRecord);
        if (envRecord.status === "LIVE") {
          const res = await api<typeof resources>(
            `/api/projects/${p.id}/environments/${envRecord.id}/resources`,
          );
          setResources(res);
        }
        const vars = await api<EnvVar[]>(
          `/api/projects/${p.id}/environments/${envRecord.id}/env-vars`,
        );
        setMissingEnvCount(
          vars.filter((v) => !v.hasValue && !v.isAutoGenerated && !v.dismissed).length,
        );
        setSuggestionCount(
          vars.filter((v) => !v.isAutoGenerated && !v.dismissed && !v.hasValue).length,
        );
      }
      setLoading(false);
    } catch (err) {
      console.error("Failed to load environment data", err);
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    params.then(({ projectSlug: slug, env }) => {
      setProjectSlug(slug);
      setEnvType(env as "staging" | "production");
      load(slug, env);
    });
  }, [params, load]);

  useIndexingComplete((payload) => {
    if (payload.projectId === project?.id) {
      setIndexing(false);
      if (payload.error) {
        setIndexingError(payload.error);
      } else {
        setIndexingError(null);
        load(projectSlug, envType);
      }
    }
  });

  useEnvironmentStatus((payload) => {
    if (payload.environmentId === environment?.id) {
      setEnvironment((e) => (e ? { ...e, status: payload.status } : e));
      if (payload.status === "LIVE" && project && environment) {
        load(projectSlug, envType);
      }
    }
  });

  const handleDeploy = (deploymentId: string) => {
    setShowDeployForm(false);
    if (project && environment) {
      router.push(
        `/projects/${projectSlug}/${envType}/deployments/${deploymentId}`,
      );
    }
  };

  const startIndexing = async () => {
    if (!project || !environment) return;
    setIndexingError(null);
    setIndexing(true);
    resetIndexEvents();
    await api(`/api/projects/${project.id}/github/index`, {
      method: "POST",
      body: JSON.stringify({ environmentId: environment.id }),
    });
  };

  if (loading || !project || !environment) {
    return (
      <div className="mx-auto max-w-5xl space-y-4 p-6">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-32 w-full rounded-lg" />
        <Skeleton className="h-64 w-full rounded-lg" />
      </div>
    );
  }

  if (!project.githubOwner) {
    return (
      <div className="mx-auto max-w-5xl p-6">
        <GitHubInstallError />
        <ConnectGitHub
          projectId={project.id}
          installationId={project.githubInstallationId}
          environmentId={environment.id}
          onRepoConnected={() => {
            setIndexingError(null);
            setIndexing(true);
            resetIndexEvents();
            void load(projectSlug, envType);
          }}
        />
      </div>
    );
  }

  if (indexing) {
    return (
      <div className="mx-auto mt-16 max-w-sm">
        <IndexingProgress events={indexEvents} />
        {indexingError && (
          <p className="mt-4 rounded-md bg-red-500/10 px-3 py-2 text-sm text-red-400">
            {indexingError}
          </p>
        )}
      </div>
    );
  }

  if (indexingError) {
    return (
      <div className="flex h-full min-h-[480px] items-center justify-center p-8">
        <div className="max-w-sm text-center">
          <h2 className="mb-2 text-base font-semibold">Indexing failed</h2>
          <p className="mb-6 text-sm text-red-400">{indexingError}</p>
          <Button onClick={startIndexing}>Try again</Button>
        </div>
      </div>
    );
  }

  if (environment.status === "DEPLOYING") {
    return (
      <DeployingState
        projectId={project.id}
        projectSlug={projectSlug}
        envType={envType}
        environmentId={environment.id}
      />
    );
  }

  if (environment.status === "LIVE" && environment.heizenConfig) {
    const outputs = environment.stackOutputs as Record<string, string> | null;
    const appUrl = outputs?.albDnsName ? `http://${outputs.albDnsName}` : null;

    return (
      <div className="mx-auto max-w-5xl space-y-6 p-6">
        <div className="flex items-center justify-between rounded-lg border border-zinc-800 bg-zinc-900 p-4">
          <div className="flex items-center gap-3">
            <span className="h-2 w-2 animate-pulse rounded-full bg-green-500" />
            <span className="text-sm font-medium capitalize">{envType}</span>
            <span className="text-sm font-medium text-green-400">Live</span>
            {environment.lastDeployedAt && (
              <span className="text-sm text-muted-foreground">
                · Last deployed {new Date(environment.lastDeployedAt).toLocaleString()}
              </span>
            )}
          </div>
          <Button size="sm" onClick={() => setShowDeployForm(true)}>
            Redeploy
          </Button>
        </div>

        <Tabs defaultValue={defaultTab}>
          <TabsList className="mb-4">
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="variables">
              Environment Variables
              {missingEnvCount > 0 && (
                <span className="ml-1.5 rounded-full bg-yellow-500/20 px-1.5 py-0.5 text-[10px] text-yellow-400">
                  {missingEnvCount}
                </span>
              )}
            </TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="space-y-6">
            <div className="grid gap-3 lg:grid-cols-2">
              <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-4">
                <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
                  Endpoints
                </p>
                {appUrl ? (
                  <div className="mt-3 space-y-2">
                    <div className="flex items-center gap-2 rounded-md border border-zinc-800 bg-zinc-950 px-3 py-2">
                      <a
                        href={appUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex-1 truncate text-sm text-blue-400 hover:underline"
                      >
                        {outputs?.albDnsName}
                      </a>
                      <CopyButton value={appUrl} />
                      <a href={appUrl} target="_blank" rel="noopener noreferrer">
                        <Button variant="ghost" size="icon" className="h-7 w-7">
                          <ExternalLink size={14} />
                        </Button>
                      </a>
                    </div>
                  </div>
                ) : (
                  <p className="mt-3 text-sm text-muted-foreground">No endpoints available yet.</p>
                )}
              </div>

              <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-4">
                <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
                  DNS Configuration
                </p>
                {environment.heizenConfig.domain && outputs?.albDnsName ? (
                  <div className="mt-3 space-y-3">
                    <div className="rounded-md border border-zinc-800 bg-zinc-950 p-3 text-sm">
                      <div className="flex items-center justify-between gap-2">
                        <span className="text-muted-foreground">Type</span>
                        <Badge variant="outline">CNAME</Badge>
                      </div>
                      <div className="mt-2 flex items-center justify-between gap-2">
                        <span className="text-muted-foreground">Name</span>
                        <span className="font-mono text-xs">{environment.heizenConfig.domain}</span>
                      </div>
                      <div className="mt-2 flex items-center justify-between gap-2">
                        <span className="text-muted-foreground">Value</span>
                        <div className="flex items-center gap-1">
                          <span className="font-mono text-xs">{outputs.albDnsName}</span>
                          <CopyButton value={outputs.albDnsName} />
                        </div>
                      </div>
                    </div>
                    <p className="text-sm text-muted-foreground">
                      Point your domain to this ALB address using a CNAME record.
                      For HTTPS, place Cloudflare or another CDN in front of this URL.
                    </p>
                  </div>
                ) : (
                  <p className="mt-3 text-sm text-muted-foreground">
                    No custom domain configured.
                  </p>
                )}
              </div>
            </div>

            <div>
              <p className="mb-3 text-sm font-medium uppercase tracking-wide text-muted-foreground">
                Infrastructure
              </p>
              <ResourceGraph resources={resources} />
            </div>
          </TabsContent>

          <TabsContent value="variables">
            <EnvVarTable projectId={project.id} envId={environment.id} />
          </TabsContent>
        </Tabs>

        {showDeployForm && (
          <DeployForm
            projectId={project.id}
            environmentId={environment.id}
            envType={envType}
            initialConfig={
              environment.heizenConfig ??
              buildDefaultHeizenConfig(projectSlug, envType)
            }
            onDeploy={handleDeploy}
            onClose={() => setShowDeployForm(false)}
          />
        )}
      </div>
    );
  }

  if (environment.heizenConfig) {
    return (
      <div className="mx-auto max-w-5xl p-6">
        <div className="grid gap-3 lg:grid-cols-3">
          <div className="lg:col-span-2">
            <IndexingResults
              config={environment.heizenConfig}
              missingEnvCount={missingEnvCount}
            />
            {suggestionCount > 0 && (
              <div className="mt-3 flex items-start gap-2 rounded-lg border border-amber-500/20 bg-amber-500/5 px-3 py-2.5">
                <span className="mt-0.5 text-xs">💡</span>
                <div>
                  <p className="text-xs text-amber-400">
                    {suggestionCount} environment variable
                    {suggestionCount !== 1 ? "s" : ""} detected
                  </p>
                  <p className="mt-0.5 text-xs text-zinc-500">
                    Open{" "}
                    <Link
                      href={`/projects/${projectSlug}/secrets`}
                      className="underline hover:text-zinc-300"
                    >
                      Secrets Manager
                    </Link>{" "}
                    to add values before deploying.
                  </p>
                </div>
              </div>
            )}
          </div>
          <div className="rounded-lg border border-zinc-800 bg-zinc-900 p-4">
            <p className="text-sm font-medium uppercase tracking-wide text-muted-foreground">
              Summary
            </p>
            <div className="mt-3">
              <CostEstimator config={environment.heizenConfig} />
            </div>
            <Button
              size="sm"
              className="mt-4 w-full"
              onClick={() => setShowDeployForm(true)}
            >
              Configure &amp; Deploy
            </Button>
            <Button
              variant="outline"
              size="sm"
              className="mt-2 w-full"
              onClick={startIndexing}
            >
              Re-index
            </Button>
          </div>
        </div>

        {showDeployForm && (
          <DeployForm
            projectId={project.id}
            environmentId={environment.id}
            envType={envType}
            initialConfig={
              environment.heizenConfig ??
              buildDefaultHeizenConfig(projectSlug, envType)
            }
            onDeploy={handleDeploy}
            onClose={() => setShowDeployForm(false)}
          />
        )}
      </div>
    );
  }

  return (
    <div className="flex h-full min-h-[480px] items-center justify-center p-8">
      <div className="max-w-sm text-center">
        <h2 className="mb-2 text-base font-semibold">Repository connected</h2>
        <p className="mb-6 text-sm text-muted-foreground">
          Ready to analyse your codebase and detect your infrastructure needs.
          You can also deploy directly with default settings.
        </p>
        <div className="flex flex-col gap-2">
          <Button onClick={startIndexing}>Analyse Codebase</Button>
          <Button variant="outline" onClick={() => setShowDeployForm(true)}>
            Deploy without indexing
          </Button>
        </div>
      </div>

      {showDeployForm && (
        <DeployForm
          projectId={project.id}
          environmentId={environment.id}
          envType={envType}
          initialConfig={buildDefaultHeizenConfig(projectSlug, envType)}
          onDeploy={handleDeploy}
          onClose={() => setShowDeployForm(false)}
        />
      )}
    </div>
  );
}
