import {
  Injectable,
  Inject,
  NotFoundException,
  BadRequestException,
  ConflictException,
  ServiceUnavailableException,
} from "@nestjs/common";
import { InjectQueue } from "@nestjs/bullmq";
import type { Queue } from "bullmq";
import type { PrismaClient } from "@heizen/db";
import { PRISMA } from "../prisma/prisma.module";
import { EnvironmentsService } from "../environments/environments.service";

@Injectable()
export class DeploymentsService {
  constructor(
    @Inject(PRISMA) private readonly prisma: PrismaClient,
    private readonly environments: EnvironmentsService,
    @InjectQueue("deployment") private readonly deploymentQueue: Queue,
  ) {}

  async create(
    orgId: string,
    projectId: string,
    envId: string,
    triggeredBy: string,
    commitSha?: string,
  ) {
    const env = await this.environments.get(orgId, projectId, envId);
    if (!env.heizenConfig) {
      throw new BadRequestException("Environment must be indexed before deploying");
    }
    if (!env.awsRoleArn || !env.region) {
      throw new BadRequestException("AWS configuration required before deploying");
    }
    if (!env.imageUri) {
      throw new BadRequestException("Docker image URI not configured");
    }

    const inFlight = await this.prisma.deployment.findFirst({
      where: {
        environmentId: envId,
        status: { in: ["QUEUED", "DEPLOYING"] },
      },
      select: { id: true, status: true },
    });
    if (inFlight) {
      throw new ConflictException(
        `Another deployment (${inFlight.id}) is already ${inFlight.status.toLowerCase()} for this environment. Wait for it to complete or cancel it.`,
      );
    }

    const missingEnvVars = await this.prisma.envVariable.findMany({
      where: {
        environmentId: envId,
        value: "",
        isAutoGenerated: false,
        dismissed: false,
      },
      select: { service: true, key: true },
    });
    if (missingEnvVars.length > 0) {
      const list = missingEnvVars.map((v) => `${v.service}.${v.key}`).join(", ");
      throw new BadRequestException(
        `Cannot deploy: env vars need values — ${list}. Set them in the Secrets tab.`,
      );
    }

    const deployment = await this.prisma.deployment.create({
      data: {
        environmentId: envId,
        triggeredBy,
        commitSha,
        status: "QUEUED",
      },
    });

    await this.prisma.environment.update({
      where: { id: envId },
      data: { status: "DEPLOYING" },
    });

    try {
      await this.deploymentQueue.add(
        "deploy",
        {
          deploymentId: deployment.id,
          environmentId: envId,
          projectId,
        },
        {
          jobId: deployment.id,
          attempts: 1,
          removeOnComplete: 50,
          removeOnFail: 100,
        },
      );
    } catch (queueErr) {
      await this.prisma.deployment.update({
        where: { id: deployment.id },
        data: {
          status: "FAILED",
          errorMessage: `Failed to enqueue: ${queueErr instanceof Error ? queueErr.message : "unknown"}`,
          completedAt: new Date(),
        },
      });
      await this.prisma.environment.update({
        where: { id: envId },
        data: { status: env.status as "LIVE" | "NOT_DEPLOYED" | "FAILED" },
      });
      throw new ServiceUnavailableException(
        "Could not enqueue deployment — the job queue may be unavailable",
      );
    }

    return deployment;
  }

  async list(orgId: string, projectId: string, envId: string) {
    await this.environments.get(orgId, projectId, envId);
    return this.prisma.deployment.findMany({
      where: { environmentId: envId },
      orderBy: { createdAt: "desc" },
    });
  }

  async get(orgId: string, projectId: string, envId: string, deployId: string) {
    await this.environments.get(orgId, projectId, envId);
    const deployment = await this.prisma.deployment.findFirst({
      where: { id: deployId, environmentId: envId },
      include: { logs: { orderBy: { timestamp: "asc" } } },
    });
    if (!deployment) throw new NotFoundException("Deployment not found");
    return deployment;
  }

  async cancel(orgId: string, projectId: string, envId: string, deployId: string) {
    const deployment = await this.get(orgId, projectId, envId, deployId);
    if (["SUCCESS", "FAILED", "CANCELLED"].includes(deployment.status)) {
      throw new BadRequestException("Deployment already finished");
    }

    const job = await this.deploymentQueue.getJob(deployId);
    if (job) {
      const state = await job.getState();
      if (state === "waiting" || state === "delayed") {
        await job.remove();
      }
      // For "active" jobs, we can't safely abort mid-Pulumi-apply.
      // The DB status flip below will at least prevent the UI from accepting more actions.
      // The processor will see the status and treat it as a failure on next checkpoint.
    }

    return this.prisma.deployment.update({
      where: { id: deployId },
      data: { status: "CANCELLED", completedAt: new Date() },
    });
  }

  async getLogs(orgId: string, projectId: string, envId: string, deployId: string) {
    await this.get(orgId, projectId, envId, deployId);
    return this.prisma.deploymentLog.findMany({
      where: { deploymentId: deployId },
      orderBy: { timestamp: "asc" },
    });
  }
}
