import {
  Injectable,
  Inject,
  NotFoundException,
  BadRequestException,
  ConflictException,
  ServiceUnavailableException,
} from "@nestjs/common";
import { InjectQueue } from "@nestjs/bullmq";
import type { Queue } from "bullmq";
import type { PrismaClient } from "@heizen/db";
import { PRISMA } from "../prisma/prisma.module";
import { EnvironmentsService } from "../environments/environments.service";
import { AuditLogService } from "../audit/audit.service";

@Injectable()
export class DeploymentsService {
  constructor(
    @Inject(PRISMA) private readonly prisma: PrismaClient,
    private readonly environments: EnvironmentsService,
    @InjectQueue("deployment") private readonly deploymentQueue: Queue,
    private readonly audit: AuditLogService,
  ) {}

  async create(
    orgId: string,
    projectId: string,
    envId: string,
    triggeredBy: string,
    commitSha?: string,
  ) {
    const env = await this.environments.get(orgId, projectId, envId);
    if (!env.heizenConfig) {
      throw new BadRequestException("Environment must be indexed before deploying");
    }
    if (!env.awsRoleArn || !env.region) {
      throw new BadRequestException("AWS configuration required before deploying");
    }
    // Only the ECS path bakes the image into a task definition. EC2 and
    // Lightsail read image refs from docker-compose.yml, so imageUri is
    // not required there. Resolve strategy the same way the worker does.
    const strategy =
      env.deployStrategy ?? (env.type === "PRODUCTION" ? "ECS" : "LIGHTSAIL");
    if (strategy === "ECS" && !env.imageUri) {
      throw new BadRequestException("Docker image URI not configured");
    }

    const inFlight = await this.prisma.deployment.findFirst({
      where: {
        environmentId: envId,
        status: { in: ["QUEUED", "DEPLOYING"] },
      },
      select: { id: true, status: true },
    });
    if (inFlight) {
      throw new ConflictException(
        `Another deployment (${inFlight.id}) is already ${inFlight.status.toLowerCase()} for this environment. Wait for it to complete or cancel it.`,
      );
    }

    const missingEnvVars = await this.prisma.envVariable.findMany({
      where: {
        environmentId: envId,
        value: "",
        isAutoGenerated: false,
        dismissed: false,
      },
      select: { service: true, key: true },
    });
    if (missingEnvVars.length > 0) {
      const list = missingEnvVars.map((v) => `${v.service}.${v.key}`).join(", ");
      throw new BadRequestException(
        `Cannot deploy: env vars need values — ${list}. Set them in the Secrets tab.`,
      );
    }

    const deployment = await this.prisma.$transaction(async (tx) => {
      const created = await tx.deployment.create({
        data: {
          environmentId: envId,
          triggeredBy,
          commitSha,
          status: "QUEUED",
        },
      });

      await tx.environment.update({
        where: { id: envId },
        data: { status: "DEPLOYING" },
      });

      await this.audit.logInTx(tx, {
        actorId: triggeredBy,
        action: "DEPLOY_TRIGGERED",
        resourceType: "ENVIRONMENT",
        resourceId: envId,
        metadata: { deploymentId: created.id, projectId, env: env.type },
      });

      return created;
    });

    try {
      await this.deploymentQueue.add(
        "deploy",
        {
          deploymentId: deployment.id,
          environmentId: envId,
          projectId,
        },
        {
          jobId: deployment.id,
          attempts: 1,
          removeOnComplete: 50,
          removeOnFail: 100,
        },
      );
    } catch (queueErr) {
      await this.prisma.deployment.update({
        where: { id: deployment.id },
        data: {
          status: "FAILED",
          errorMessage: `Failed to enqueue: ${queueErr instanceof Error ? queueErr.message : "unknown"}`,
          completedAt: new Date(),
        },
      });
      await this.prisma.environment.update({
        where: { id: envId },
        data: { status: env.status as "LIVE" | "NOT_DEPLOYED" | "FAILED" },
      });
      throw new ServiceUnavailableException(
        "Could not enqueue deployment — the job queue may be unavailable",
      );
    }

    return deployment;
  }

  /**
   * Roll back to the previous good commit: redeploy the most recent
   * successful deployment whose commit differs from what's currently
   * running. Reuses create() so all the usual guards (indexed, AWS
   * configured, no in-flight job, env vars set) still apply.
   */
  async rollback(
    orgId: string,
    projectId: string,
    envId: string,
    triggeredBy: string,
  ) {
    await this.environments.get(orgId, projectId, envId);

    const successes = await this.prisma.deployment.findMany({
      where: {
        environmentId: envId,
        kind: "DEPLOY",
        status: "SUCCESS",
        commitSha: { not: null },
      },
      orderBy: { completedAt: "desc" },
      take: 10,
      select: { commitSha: true },
    });

    // The most recent successful deploy is what's live: an in-flight or
    // failed deploy doesn't replace the running version, so it's the right
    // "current" to roll back away from.
    const currentSha = successes[0]?.commitSha ?? null;
    const target = successes.find(
      (d) => d.commitSha && d.commitSha !== currentSha,
    );
    if (!target?.commitSha) {
      if (successes.length === 0) {
        throw new BadRequestException(
          "No successful deployments yet — nothing to roll back to.",
        );
      }
      throw new BadRequestException(
        "No earlier successful deployment on a different commit to roll back to.",
      );
    }

    return this.create(orgId, projectId, envId, triggeredBy, target.commitSha);
  }

  async destroy(
    orgId: string,
    projectId: string,
    envId: string,
    triggeredBy: string,
  ) {
    const env = await this.environments.get(orgId, projectId, envId);

    // Nothing to tear down — env was never deployed or is already a
    // tombstone. Refusing here keeps the audit log clean and avoids a
    // queued job that would immediately fail.
    if (env.status === "NOT_DEPLOYED" || env.status === "DESTROYED") {
      throw new BadRequestException(
        `Environment is ${env.status.toLowerCase()} — nothing to destroy.`,
      );
    }
    if (!env.heizenConfig) {
      throw new BadRequestException(
        "Environment has no rendered config — was it ever deployed?",
      );
    }
    if (!env.awsRoleArn || !env.region) {
      throw new BadRequestException(
        "AWS configuration missing — can't reach the stack to destroy it.",
      );
    }
    if (!env.pulumiBackendBucket || !env.pulumiStackName) {
      throw new BadRequestException(
        "Stack metadata missing — env was never deployed, nothing to destroy.",
      );
    }

    // Same in-flight check as create(): one Pulumi operation at a time
    // per environment. A second destroy clashes; a deploy mid-destroy
    // is even worse.
    const inFlight = await this.prisma.deployment.findFirst({
      where: {
        environmentId: envId,
        status: { in: ["QUEUED", "DEPLOYING"] },
      },
      select: { id: true, status: true, kind: true },
    });
    if (inFlight) {
      throw new ConflictException(
        `Another ${inFlight.kind.toLowerCase()} (${inFlight.id}) is already ${inFlight.status.toLowerCase()}. Wait for it to complete or cancel it.`,
      );
    }

    const deployment = await this.prisma.$transaction(async (tx) => {
      const created = await tx.deployment.create({
        data: {
          environmentId: envId,
          triggeredBy,
          kind: "DESTROY",
          status: "QUEUED",
        },
      });

      await tx.environment.update({
        where: { id: envId },
        data: { status: "DESTROYING" },
      });

      await this.audit.logInTx(tx, {
        actorId: triggeredBy,
        action: "DESTROY_TRIGGERED",
        resourceType: "ENVIRONMENT",
        resourceId: envId,
        metadata: { deploymentId: created.id, projectId, env: env.type },
      });

      return created;
    });

    try {
      await this.deploymentQueue.add(
        "deploy",
        {
          deploymentId: deployment.id,
          environmentId: envId,
          projectId,
        },
        {
          jobId: deployment.id,
          attempts: 1,
          removeOnComplete: 50,
          removeOnFail: 100,
        },
      );
    } catch (queueErr) {
      await this.prisma.deployment.update({
        where: { id: deployment.id },
        data: {
          status: "FAILED",
          errorMessage: `Failed to enqueue: ${queueErr instanceof Error ? queueErr.message : "unknown"}`,
          completedAt: new Date(),
        },
      });
      await this.prisma.environment.update({
        where: { id: envId },
        data: { status: env.status as "LIVE" | "FAILED" | "NOT_DEPLOYED" },
      });
      throw new ServiceUnavailableException(
        "Could not enqueue destroy — the job queue may be unavailable",
      );
    }

    return deployment;
  }

  async list(orgId: string, projectId: string, envId: string) {
    await this.environments.get(orgId, projectId, envId);
    return this.prisma.deployment.findMany({
      where: { environmentId: envId },
      orderBy: { createdAt: "desc" },
    });
  }

  async get(orgId: string, projectId: string, envId: string, deployId: string) {
    await this.environments.get(orgId, projectId, envId);
    const deployment = await this.prisma.deployment.findFirst({
      where: { id: deployId, environmentId: envId },
      include: { logs: { orderBy: { timestamp: "asc" } } },
    });
    if (!deployment) throw new NotFoundException("Deployment not found");
    return deployment;
  }

  async cancel(orgId: string, projectId: string, envId: string, deployId: string) {
    const deployment = await this.get(orgId, projectId, envId, deployId);
    if (["SUCCESS", "FAILED", "CANCELLED"].includes(deployment.status)) {
      throw new BadRequestException("Deployment already finished");
    }

    const job = await this.deploymentQueue.getJob(deployId);
    if (job) {
      const state = await job.getState();
      if (state === "waiting" || state === "delayed") {
        await job.remove();
      }
      // For "active" jobs, we can't safely abort mid-Pulumi-apply.
      // The DB status flip below will at least prevent the UI from accepting more actions.
      // The processor will see the status and treat it as a failure on next checkpoint.
    }

    return this.prisma.deployment.update({
      where: { id: deployId },
      data: { status: "CANCELLED", completedAt: new Date() },
    });
  }

  async getLogs(orgId: string, projectId: string, envId: string, deployId: string) {
    await this.get(orgId, projectId, envId, deployId);
    return this.prisma.deploymentLog.findMany({
      where: { deploymentId: deployId },
      orderBy: { timestamp: "asc" },
    });
  }
}
