"use client";

import { Suspense, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import {
  KeyRound, Eye, EyeOff, Plus, X, Check, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState } from "@/components/ui/empty-state";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";
import type { HeizenConfig } from "@heizen/shared";

function getAutoInjectedKeys(
  config: HeizenConfig | null,
): Array<{ key: string; description: string; active: boolean }> {
  const hasPostgres = config?.database.engine === "postgres";
  const hasRedis = config?.cache.engine === "redis";
  const hasStorage = config?.storage.enabled ?? false;

  return [
    {
      key: "DATABASE_URL",
      active: hasPostgres,
      description: hasPostgres
        ? "Postgres enabled — built from your RDS endpoint + credentials"
        : "Injected when Postgres is enabled in your stack",
    },
    {
      key: "REDIS_URL",
      active: hasRedis,
      description: hasRedis
        ? "Redis enabled — built from your ElastiCache endpoint"
        : "Injected when Redis is enabled in your stack",
    },
    {
      key: "AWS_S3_BUCKET",
      active: hasStorage,
      description: hasStorage
        ? "S3 storage enabled — your bucket name"
        : "Injected when S3 storage is enabled in your stack",
    },
    {
      key: "NODE_ENV",
      active: true,
      description: 'Always set to "production"',
    },
  ];
}

interface EnvVar {
  id: string;
  service: string;
  key: string;
  hasValue: boolean;
  isAutoGenerated: boolean;
  dismissed: boolean;
}

interface Project {
  id: string;
  slug: string;
  environments: Array<{ id: string; type: string; heizenConfig: HeizenConfig | null }>;
}

function SecretRow({
  secret,
  onSave,
  onDismiss,
  isSuggestion = false,
  confirmingDelete = false,
  onDeleteRequest,
  onDeleteConfirm,
  onDeleteCancel,
}: {
  secret: EnvVar;
  onSave: (id: string, value: string) => Promise<void>;
  onDismiss?: (id: string) => Promise<void>;
  isSuggestion?: boolean;
  confirmingDelete?: boolean;
  onDeleteRequest?: (id: string) => void;
  onDeleteConfirm?: (id: string) => Promise<void>;
  onDeleteCancel?: () => void;
}) {
  const [editing, setEditing] = useState(false);
  const [inputValue, setInputValue] = useState("");
  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleSave = async () => {
    if (!inputValue.trim()) return;
    setSaving(true);
    try {
      await onSave(secret.id, inputValue.trim());
      setSaved(true);
      setEditing(false);
      setInputValue("");
      setTimeout(() => setSaved(false), 2000);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div
      className={cn(
        "flex items-center gap-3 rounded-lg border px-4 py-3",
        isSuggestion
          ? "border-warning/20 bg-warning/5"
          : "border-border bg-card/50",
      )}
    >
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <code className="font-mono text-xs font-medium text-foreground">
            {secret.key}
          </code>
          {isSuggestion && (
            <Badge
              variant="outline"
              className="border-warning/30 text-[10px] text-warning-foreground"
            >
              detected
            </Badge>
          )}
          {saved && (
            <span className="flex items-center gap-1 text-[11px] text-success">
              <Check size={11} /> saved
            </span>
          )}
        </div>

        {editing ? (
          <div className="mt-2 flex gap-2">
            <div className="relative flex-1">
              <Input
                type={show ? "text" : "password"}
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSave()}
                placeholder="Enter value..."
                className="h-8 pr-8 font-mono text-xs"
                autoFocus
              />
              <button
                type="button"
                onClick={() => setShow((s) => !s)}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              >
                {show ? <EyeOff size={13} /> : <Eye size={13} />}
              </button>
            </div>
            <Button
              size="sm"
              onClick={handleSave}
              disabled={saving || !inputValue.trim()}
              className="h-8 text-xs"
            >
              {saving ? "Saving..." : "Save"}
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onClick={() => { setEditing(false); setInputValue(""); }}
              className="h-8 text-xs"
            >
              Cancel
            </Button>
          </div>
        ) : (
          <p className="mt-0.5 text-xs text-muted-foreground">
            {secret.hasValue ? "••••••••••••" : "No value set"}
          </p>
        )}
      </div>

      <div className="flex shrink-0 items-center gap-1">
        {!editing && (
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setEditing(true)}
            className="h-7 text-xs text-muted-foreground hover:text-foreground"
          >
            {secret.hasValue ? "Edit" : "Set"}
          </Button>
        )}
        {isSuggestion && onDismiss && (
          <Button
            size="sm"
            variant="ghost"
            onClick={() => onDismiss(secret.id)}
            className="h-7 text-muted-foreground hover:text-foreground/90"
            aria-label="Dismiss"
          >
            <X size={12} />
          </Button>
        )}
        {!isSuggestion && onDeleteRequest && onDeleteConfirm && onDeleteCancel && (
          confirmingDelete ? (
            <div className="flex items-center gap-1">
              <span className="text-xs text-muted-foreground">Delete?</span>
              <Button
                size="sm"
                variant="ghost"
                onClick={() => onDeleteConfirm(secret.id)}
                className="h-7 text-xs text-destructive hover:text-destructive/80"
              >
                Yes
              </Button>
              <Button
                size="sm"
                variant="ghost"
                onClick={onDeleteCancel}
                className="h-7 text-xs text-muted-foreground"
              >
                No
              </Button>
            </div>
          ) : (
            <Button
              size="sm"
              variant="ghost"
              onClick={() => onDeleteRequest(secret.id)}
              className="h-7 text-destructive/60 hover:text-destructive"
              aria-label="Delete"
            >
              <X size={12} />
            </Button>
          )
        )}
      </div>
    </div>
  );
}

function AddSecretForm({ onAdd }: { onAdd: (key: string, value: string) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [key, setKey] = useState("");
  const [value, setValue] = useState("");
  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);
  const [addError, setAddError] = useState<string | null>(null);

  const handleAdd = async () => {
    if (!key.trim() || !value.trim()) return;
    setSaving(true);
    setAddError(null);
    try {
      await onAdd(
        key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "_"),
        value.trim(),
      );
      setKey("");
      setValue("");
      setOpen(false);
    } catch (err) {
      setAddError(
        err instanceof Error && err.message.includes("already")
          ? "A secret with this key already exists."
          : "Failed to add secret. Try again.",
      );
    } finally {
      setSaving(false);
    }
  };

  if (!open) {
    return (
      <Button size="sm" variant="outline" onClick={() => setOpen(true)} className="gap-1.5">
        <Plus size={13} /> Add Secret
      </Button>
    );
  }

  return (
    <div className="rounded-lg border border-foreground/20 bg-card p-4">
      <p className="mb-3 text-xs font-medium text-muted-foreground">New Secret</p>
      <div className="space-y-2">
        <div className="space-y-1.5">
          <Label htmlFor="secret-key">Key</Label>
          <Input
            id="secret-key"
            value={key}
            onChange={(e) => setKey(e.target.value)}
            placeholder="DATABASE_URL"
            className="font-mono text-xs"
            autoFocus
          />
          <p className="text-xs text-muted-foreground">
            Uppercase letters, numbers, and underscores
          </p>
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="secret-value">Value</Label>
          <div className="relative">
            <Input
              id="secret-value"
              type={show ? "text" : "password"}
              value={value}
              onChange={(e) => setValue(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleAdd()}
              placeholder="Enter value..."
              className="pr-8 font-mono text-xs"
            />
            <button
              type="button"
              onClick={() => setShow((s) => !s)}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
            >
              {show ? <EyeOff size={13} /> : <Eye size={13} />}
            </button>
          </div>
        </div>
        <div className="flex gap-2">
          <Button
            size="sm"
            onClick={handleAdd}
            disabled={saving || !key.trim() || !value.trim()}
            className="flex-1"
          >
            {saving ? "Adding..." : "Add"}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => { setOpen(false); setKey(""); setValue(""); setAddError(null); }}
          >
            Cancel
          </Button>
        </div>
        {addError && (
          <p className="text-xs text-destructive">{addError}</p>
        )}
      </div>
    </div>
  );
}

function SecretsContent() {
  const params = useParams<{ projectSlug: string }>();
  const [project, setProject] = useState<Project | null>(null);
  const [activeEnv, setActiveEnv] = useState<"PRODUCTION" | "STAGING">("PRODUCTION");
  const [vars, setVars] = useState<EnvVar[]>([]);
  const [loading, setLoading] = useState(true);
  const [varsLoading, setVarsLoading] = useState(false);
  const [deleteConfirm, setDeleteConfirm] = useState<string | null>(null);

  const activeEnvironment = project?.environments.find((e) => e.type === activeEnv);

  useEffect(() => {
    api<Array<{
      id: string;
      slug: string;
      environments: Array<{ id: string; type: string; heizenConfig: HeizenConfig | null }>;
    }>>("/api/projects")
      .then((projects) => {
        const p = projects.find((pr) => pr.slug === params.projectSlug);
        if (p) setProject(p);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [params.projectSlug]);

  useEffect(() => {
    if (!project) return;
    const env = project.environments.find((e) => e.type === activeEnv);
    if (!env) return;
    let cancelled = false;
    setVarsLoading(true);
    api<EnvVar[]>(
      `/api/projects/${project.id}/environments/${env.id}/env-vars`,
    )
      .then((data) => { if (!cancelled) setVars(data); })
      .catch(() => {})
      .finally(() => { if (!cancelled) setVarsLoading(false); });
    return () => { cancelled = true; };
  }, [project, activeEnv]);

  const reloadVars = async () => {
    if (!project || !activeEnvironment) return;
    try {
      const data = await api<EnvVar[]>(
        `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars`,
      );
      setVars(data);
    } catch {
      // Reload failed after mutation — stale UI is acceptable,
      // the action (save/delete/dismiss) already completed successfully.
    }
  };

  const handleSave = async (varId: string, value: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars/${varId}`,
      { method: "PATCH", body: JSON.stringify({ value }) },
    );
    await reloadVars();
  };

  const handleDelete = async (varId: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars/${varId}`,
      { method: "DELETE" },
    );
    setDeleteConfirm(null);
    await reloadVars();
  };

  const handleDismiss = async (varId: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars/${varId}/dismiss`,
      { method: "PATCH" },
    );
    await reloadVars();
  };

  const handleAdd = async (key: string, value: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars`,
      { method: "POST", body: JSON.stringify({ service: "shared", key, value }) },
    );
    await reloadVars();
  };

  if (loading) {
    return (
      <div className="mx-auto max-w-3xl space-y-4 p-6">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-48 rounded-lg" />
        <Skeleton className="h-48 rounded-lg" />
      </div>
    );
  }

  const suggestions = vars.filter((v) => !v.isAutoGenerated && !v.dismissed && !v.hasValue);
  const userSecrets = vars.filter((v) => !v.isAutoGenerated && v.hasValue);
  const missingCount = suggestions.length;
  const heizenConfig = activeEnvironment?.heizenConfig ?? null;
  const autoInjectedKeys = getAutoInjectedKeys(heizenConfig);

  return (
    <div className="mx-auto max-w-3xl space-y-8 p-6">

      {/* Header + env switcher */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <KeyRound size={16} className="text-muted-foreground" />
          <h1 className="text-base font-semibold">Secrets</h1>
        </div>
        <div className="flex items-center gap-3">
          {varsLoading && (
            <div className="h-3 w-3 animate-spin rounded-full border border-border border-t-foreground/90" />
          )}
          <div className="flex rounded-md border border-border bg-card p-0.5">
            {(["PRODUCTION", "STAGING"] as const).map((env) => (
              <button
                key={env}
                onClick={() => !varsLoading && setActiveEnv(env)}
                className={cn(
                  "rounded px-3 py-1 text-xs font-medium transition-colors",
                  activeEnv === env
                    ? "bg-muted text-foreground"
                    : "text-muted-foreground hover:text-foreground",
                  varsLoading && "cursor-not-allowed opacity-50",
                )}
              >
                {env.charAt(0) + env.slice(1).toLowerCase()}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Info callout */}
      <div className="flex items-start gap-3 rounded-lg border border-border bg-card/50 px-4 py-3">
        <Zap size={14} className="mt-0.5 shrink-0 text-info" />
        <p className="text-xs leading-relaxed text-muted-foreground">
          Secrets are encrypted and injected as environment variables into all
          ECS containers at deploy time. Your app reads them via{" "}
          <code className="text-foreground/90">process.env.KEY_NAME</code>.
        </p>
      </div>

      {/* Suggestions */}
      {suggestions.length > 0 && (
        <section className="space-y-3">
          <div>
            <p className="text-sm font-medium text-warning-foreground">
              💡 Detected in your codebase
            </p>
            <p className="mt-0.5 text-xs text-muted-foreground">
              These keys were found during analysis. Add values or dismiss
              the ones you don&apos;t need.
            </p>
          </div>
          <div className="space-y-2">
            {suggestions.map((v) => (
              <SecretRow
                key={v.id}
                secret={v}
                onSave={handleSave}
                onDismiss={handleDismiss}
                isSuggestion
              />
            ))}
          </div>
        </section>
      )}

      {/* Auto-injected */}
      <section className="space-y-3">
        <p className="text-sm font-medium text-muted-foreground">
          ⚡ Auto-injected by Heizen
        </p>
        <div className="rounded-lg border border-border bg-card/30 px-4 py-3">
          <p className="mb-3 text-xs text-muted-foreground">
            {heizenConfig
              ? "Injected at deploy time based on your stack — only keys that apply to this environment are set."
              : "After indexing your codebase, Heizen injects variables that match your stack (Postgres, Redis, S3, etc.)."}
          </p>
          <div className="space-y-2">
            {autoInjectedKeys.map((item) => (
              <div
                key={item.key}
                className={cn(
                  "flex items-start justify-between gap-4 rounded-md px-2 py-1.5",
                  item.active ? "bg-card/40" : "opacity-60",
                )}
              >
                <code className="shrink-0 font-mono text-xs font-medium text-foreground">
                  {item.key}
                </code>
                <span className="text-right text-xs text-muted-foreground">{item.description}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* User secrets */}
      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-medium text-foreground/90">Your Secrets</p>
          <AddSecretForm onAdd={handleAdd} />
        </div>
        {userSecrets.length === 0 ? (
          <EmptyState
            icon={KeyRound}
            title="No secrets added yet"
            description="Add any key-value pair your app needs at runtime."
            className="py-8"
          />
        ) : (
          <div className="space-y-2">
            {userSecrets.map((v) => (
              <SecretRow
                key={v.id}
                secret={v}
                onSave={handleSave}
                onDeleteRequest={(id) => setDeleteConfirm(id)}
                onDeleteConfirm={handleDelete}
                onDeleteCancel={() => setDeleteConfirm(null)}
                confirmingDelete={deleteConfirm === v.id}
              />
            ))}
          </div>
        )}
      </section>

      {/* Missing secrets warning */}
      {missingCount > 0 && (
        <div className="rounded-lg border border-warning/20 bg-warning/5 px-4 py-3">
          <p className="text-sm font-medium text-warning-foreground">
            ⚠ {missingCount} detected secret{missingCount !== 1 ? "s" : ""} have no value
          </p>
          <p className="mt-1 text-xs text-muted-foreground">
            These will be empty strings in your containers at deploy time.
            Fill them in above or dismiss them if not needed.
          </p>
        </div>
      )}
    </div>
  );
}

export default function SecretsPage() {
  return (
    <Suspense
      fallback={
        <div className="mx-auto max-w-3xl space-y-4 p-6">
          <Skeleton className="h-8 w-48" />
          <Skeleton className="h-96 rounded-lg" />
        </div>
      }
    >
      <SecretsContent />
    </Suspense>
  );
}
