"use client";

import { Suspense, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import {
  KeyRound, Eye, EyeOff, Plus, X, Check, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";
import { api } from "@/lib/api";
import type { HeizenConfig } from "@heizen/shared";

function getAutoInjectedKeys(
  config: HeizenConfig | null,
  envType: "PRODUCTION" | "STAGING",
): Array<{ key: string; description: string; active: boolean }> {
  const hasPostgres = config?.database.engine === "postgres";
  const hasRedis = config?.cache.engine === "redis";
  const hasStorage = config?.storage.enabled ?? false;

  return [
    {
      key: "DATABASE_URL",
      active: hasPostgres,
      description: hasPostgres
        ? "Postgres enabled — built from your RDS endpoint + credentials"
        : "Injected when Postgres is enabled in your stack",
    },
    {
      key: "REDIS_URL",
      active: hasRedis,
      description: hasRedis
        ? "Redis enabled — built from your ElastiCache endpoint"
        : "Injected when Redis is enabled in your stack",
    },
    {
      key: "AWS_S3_BUCKET",
      active: hasStorage,
      description: hasStorage
        ? "S3 storage enabled — your bucket name"
        : "Injected when S3 storage is enabled in your stack",
    },
    {
      key: "NODE_ENV",
      active: true,
      description:
        envType === "STAGING"
          ? 'Always set to "development" in staging'
          : 'Always set to "production" in production',
    },
  ];
}

interface EnvVar {
  id: string;
  service: string;
  key: string;
  hasValue: boolean;
  isAutoGenerated: boolean;
  dismissed: boolean;
}

interface Project {
  id: string;
  slug: string;
  environments: Array<{ id: string; type: string; heizenConfig: HeizenConfig | null }>;
}

function SecretRow({
  secret,
  onSave,
  onDelete,
  onDismiss,
  isSuggestion = false,
}: {
  secret: EnvVar;
  onSave: (id: string, value: string) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
  onDismiss?: (id: string) => Promise<void>;
  isSuggestion?: boolean;
}) {
  const [editing, setEditing] = useState(isSuggestion && !secret.hasValue);
  const [inputValue, setInputValue] = useState("");
  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);

  const handleSave = async () => {
    if (!inputValue.trim()) return;
    setSaving(true);
    try {
      await onSave(secret.id, inputValue.trim());
      setSaved(true);
      setEditing(false);
      setInputValue("");
      setTimeout(() => setSaved(false), 2000);
    } finally {
      setSaving(false);
    }
  };

  return (
    <div
      className={cn(
        "flex items-center gap-3 rounded-lg border px-4 py-3",
        isSuggestion
          ? "border-amber-500/20 bg-amber-500/5"
          : "border-zinc-800 bg-zinc-900/50",
      )}
    >
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <code className="font-mono text-xs font-medium text-zinc-200">
            {secret.key}
          </code>
          {isSuggestion && (
            <Badge
              variant="outline"
              className="border-amber-500/30 text-[10px] text-amber-400"
            >
              detected
            </Badge>
          )}
          {saved && (
            <span className="flex items-center gap-1 text-[11px] text-green-400">
              <Check size={11} /> saved
            </span>
          )}
        </div>

        {editing ? (
          <div className="mt-2 flex gap-2">
            <div className="relative flex-1">
              <Input
                type={show ? "text" : "password"}
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSave()}
                placeholder="Enter value..."
                className="h-8 pr-8 font-mono text-xs"
                autoFocus
              />
              <button
                type="button"
                onClick={() => setShow((s) => !s)}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
              >
                {show ? <EyeOff size={13} /> : <Eye size={13} />}
              </button>
            </div>
            <Button
              size="sm"
              onClick={handleSave}
              disabled={saving || !inputValue.trim()}
              className="h-8 text-xs"
            >
              {saving ? "Saving..." : "Save"}
            </Button>
            {!isSuggestion && (
              <Button
                size="sm"
                variant="ghost"
                onClick={() => { setEditing(false); setInputValue(""); }}
                className="h-8 text-xs"
              >
                Cancel
              </Button>
            )}
          </div>
        ) : (
          <p className="mt-0.5 text-xs text-zinc-500">
            {secret.hasValue ? "••••••••••••" : "No value set"}
          </p>
        )}
      </div>

      <div className="flex shrink-0 items-center gap-1">
        {!editing && (
          <Button
            size="sm"
            variant="ghost"
            onClick={() => setEditing(true)}
            className="h-7 text-xs text-zinc-400 hover:text-white"
          >
            {secret.hasValue ? "Edit" : "Set"}
          </Button>
        )}
        {isSuggestion && onDismiss && (
          <Button
            size="sm"
            variant="ghost"
            onClick={() => onDismiss(secret.id)}
            className="h-7 text-zinc-500 hover:text-zinc-300"
            aria-label="Dismiss"
          >
            <X size={12} />
          </Button>
        )}
        {!isSuggestion && (
          <Button
            size="sm"
            variant="ghost"
            onClick={() => onDelete(secret.id)}
            className="h-7 text-red-400/60 hover:text-red-400"
            aria-label="Delete"
          >
            <X size={12} />
          </Button>
        )}
      </div>
    </div>
  );
}

function AddSecretForm({ onAdd }: { onAdd: (key: string, value: string) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [key, setKey] = useState("");
  const [value, setValue] = useState("");
  const [show, setShow] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleAdd = async () => {
    if (!key.trim() || !value.trim()) return;
    setSaving(true);
    try {
      await onAdd(
        key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "_"),
        value.trim(),
      );
      setKey("");
      setValue("");
      setOpen(false);
    } finally {
      setSaving(false);
    }
  };

  if (!open) {
    return (
      <Button size="sm" variant="outline" onClick={() => setOpen(true)} className="gap-1.5">
        <Plus size={13} /> Add Secret
      </Button>
    );
  }

  return (
    <div className="rounded-lg border border-zinc-700 bg-zinc-900 p-4">
      <p className="mb-3 text-xs font-medium text-zinc-400">New Secret</p>
      <div className="space-y-2">
        <Input
          value={key}
          onChange={(e) => setKey(e.target.value)}
          placeholder="KEY_NAME"
          className="font-mono text-xs"
          autoFocus
        />
        <div className="relative">
          <Input
            type={show ? "text" : "password"}
            value={value}
            onChange={(e) => setValue(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleAdd()}
            placeholder="value"
            className="pr-8 font-mono text-xs"
          />
          <button
            type="button"
            onClick={() => setShow((s) => !s)}
            className="absolute right-2 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
          >
            {show ? <EyeOff size={13} /> : <Eye size={13} />}
          </button>
        </div>
        <div className="flex gap-2">
          <Button
            size="sm"
            onClick={handleAdd}
            disabled={saving || !key.trim() || !value.trim()}
            className="flex-1"
          >
            {saving ? "Adding..." : "Add"}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            onClick={() => { setOpen(false); setKey(""); setValue(""); }}
          >
            Cancel
          </Button>
        </div>
      </div>
    </div>
  );
}

function SecretsContent() {
  const params = useParams<{ projectSlug: string }>();
  const [project, setProject] = useState<Project | null>(null);
  const [activeEnv, setActiveEnv] = useState<"PRODUCTION" | "STAGING">("PRODUCTION");
  const [vars, setVars] = useState<EnvVar[]>([]);
  const [loading, setLoading] = useState(true);

  const activeEnvironment = project?.environments.find((e) => e.type === activeEnv);

  const loadVars = useCallback(async (projId: string, envId: string) => {
    const data = await api<EnvVar[]>(
      `/api/projects/${projId}/environments/${envId}/env-vars`,
    );
    setVars(data);
  }, []);

  useEffect(() => {
    api<Array<{ id: string; slug: string; environments: Array<{ id: string; type: string; heizenConfig: HeizenConfig | null }> }>>(
      "/api/projects",
    )
      .then((projects) => {
        const p = projects.find((pr) => pr.slug === params.projectSlug);
        if (p) {
          setProject(p);
          const prod = p.environments.find((e) => e.type === "PRODUCTION");
          if (prod) loadVars(p.id, prod.id);
        }
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [params.projectSlug, loadVars]);

  useEffect(() => {
    if (project && activeEnvironment) {
      loadVars(project.id, activeEnvironment.id);
    }
  }, [activeEnv, project, activeEnvironment, loadVars]);

  const handleSave = async (varId: string, value: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars/${varId}`,
      { method: "PATCH", body: JSON.stringify({ value }) },
    );
    await loadVars(project.id, activeEnvironment.id);
  };

  const handleDelete = async (varId: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars/${varId}`,
      { method: "DELETE" },
    );
    await loadVars(project.id, activeEnvironment.id);
  };

  const handleDismiss = async (varId: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars/${varId}/dismiss`,
      { method: "PATCH" },
    );
    await loadVars(project.id, activeEnvironment.id);
  };

  const handleAdd = async (key: string, value: string) => {
    if (!project || !activeEnvironment) return;
    await api(
      `/api/projects/${project.id}/environments/${activeEnvironment.id}/env-vars`,
      { method: "POST", body: JSON.stringify({ service: "shared", key, value }) },
    );
    await loadVars(project.id, activeEnvironment.id);
  };

  if (loading) {
    return (
      <div className="mx-auto max-w-3xl space-y-4 p-6">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-48 rounded-lg" />
        <Skeleton className="h-48 rounded-lg" />
      </div>
    );
  }

  const suggestions = vars.filter((v) => !v.isAutoGenerated && !v.dismissed && !v.hasValue);
  const userSecrets  = vars.filter((v) => !v.isAutoGenerated && (v.hasValue || v.dismissed === false) && !((!v.dismissed) && (!v.hasValue)));
  const missingCount = suggestions.length;
  const heizenConfig = activeEnvironment?.heizenConfig ?? null;
  const autoInjectedKeys = getAutoInjectedKeys(heizenConfig, activeEnv);

  return (
    <div className="mx-auto max-w-3xl space-y-8 p-6">

      {/* Header + env switcher */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <KeyRound size={16} className="text-zinc-400" />
          <h1 className="text-base font-semibold">Secrets</h1>
        </div>
        <div className="flex rounded-md border border-zinc-800 bg-zinc-900 p-0.5">
          {(["PRODUCTION", "STAGING"] as const).map((env) => (
            <button
              key={env}
              onClick={() => setActiveEnv(env)}
              className={cn(
                "rounded px-3 py-1 text-xs font-medium transition-colors",
                activeEnv === env
                  ? "bg-zinc-700 text-white"
                  : "text-zinc-400 hover:text-zinc-200",
              )}
            >
              {env.charAt(0) + env.slice(1).toLowerCase()}
            </button>
          ))}
        </div>
      </div>

      {/* Info callout */}
      <div className="flex items-start gap-3 rounded-lg border border-zinc-800 bg-zinc-900/50 px-4 py-3">
        <Zap size={14} className="mt-0.5 shrink-0 text-blue-400" />
        <p className="text-xs leading-relaxed text-zinc-400">
          Secrets are encrypted and injected as environment variables into all
          ECS containers at deploy time. Your app reads them via{" "}
          <code className="text-zinc-300">process.env.KEY_NAME</code>.
        </p>
      </div>

      {/* Suggestions */}
      {suggestions.length > 0 && (
        <section className="space-y-3">
          <div>
            <p className="text-sm font-medium text-amber-400">
              💡 Detected in your codebase
            </p>
            <p className="mt-0.5 text-xs text-zinc-500">
              These keys were found during analysis. Add values or dismiss
              the ones you don&apos;t need.
            </p>
          </div>
          <div className="space-y-2">
            {suggestions.map((v) => (
              <SecretRow
                key={v.id}
                secret={v}
                onSave={handleSave}
                onDelete={handleDelete}
                onDismiss={handleDismiss}
                isSuggestion
              />
            ))}
          </div>
        </section>
      )}

      {/* Auto-injected */}
      <section className="space-y-3">
        <p className="text-sm font-medium text-zinc-400">
          ⚡ Auto-injected by Heizen
        </p>
        <div className="rounded-lg border border-zinc-800 bg-zinc-900/30 px-4 py-3">
          <p className="mb-3 text-xs text-zinc-500">
            {heizenConfig
              ? "Injected at deploy time based on your stack — only keys that apply to this environment are set."
              : "After indexing your codebase, Heizen injects variables that match your stack (Postgres, Redis, S3, etc.)."}
          </p>
          <div className="space-y-2">
            {autoInjectedKeys.map((item) => (
              <div
                key={item.key}
                className={cn(
                  "flex items-start justify-between gap-4 rounded-md px-2 py-1.5",
                  item.active ? "bg-zinc-900/40" : "opacity-60",
                )}
              >
                <code className="shrink-0 font-mono text-xs font-medium text-zinc-200">
                  {item.key}
                </code>
                <span className="text-right text-xs text-zinc-500">{item.description}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* User secrets */}
      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-sm font-medium text-zinc-300">Your Secrets</p>
          <AddSecretForm onAdd={handleAdd} />
        </div>
        {userSecrets.length === 0 ? (
          <div className="rounded-lg border border-dashed border-zinc-800 py-8 text-center">
            <p className="text-sm text-zinc-500">No secrets added yet.</p>
            <p className="mt-1 text-xs text-zinc-600">
              Add any key-value pair your app needs at runtime.
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            {userSecrets.map((v) => (
              <SecretRow
                key={v.id}
                secret={v}
                onSave={handleSave}
                onDelete={handleDelete}
              />
            ))}
          </div>
        )}
      </section>

      {/* Missing secrets warning */}
      {missingCount > 0 && (
        <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 px-4 py-3">
          <p className="text-sm font-medium text-amber-400">
            ⚠ {missingCount} detected secret{missingCount !== 1 ? "s" : ""} have no value
          </p>
          <p className="mt-1 text-xs text-zinc-400">
            These will be empty strings in your containers at deploy time.
            Fill them in above or dismiss them if not needed.
          </p>
        </div>
      )}
    </div>
  );
}

export default function SecretsPage() {
  return (
    <Suspense
      fallback={
        <div className="mx-auto max-w-3xl space-y-4 p-6">
          <Skeleton className="h-8 w-48" />
          <Skeleton className="h-96 rounded-lg" />
        </div>
      }
    >
      <SecretsContent />
    </Suspense>
  );
}
