"use client";

import { useEffect, useState } from "react";
import type { HeizenConfig } from "@heizen/shared";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { CostEstimator } from "./CostEstimator";
import { api } from "@/lib/api";

interface Props {
  projectId: string;
  environmentId: string;
  envType: "staging" | "production";
  initialConfig: HeizenConfig;
  onDeploy: (deploymentId: string) => void;
  onClose: () => void;
}

export function DeployForm({
  projectId,
  environmentId,
  envType,
  initialConfig,
  onDeploy,
  onClose,
}: Props) {
  const [step, setStep] = useState(1);
  const [config, setConfig] = useState<HeizenConfig>(initialConfig);
  const [awsAccountId, setAwsAccountId] = useState("");
  const [awsRoleArn, setAwsRoleArn] = useState("");
  const [verifyResult, setVerifyResult] = useState<string | null>(null);
  const [verifyError, setVerifyError] = useState<string | null>(null);
  const [envVars, setEnvVars] = useState<
    Array<{ service: string; key: string; value: string }>
  >([]);
  const [deploying, setDeploying] = useState(false);
  const [deployError, setDeployError] = useState<string | null>(null);

  useEffect(() => {
    api<
      Array<{ service: string; key: string; hasValue: boolean; isAutoGenerated: boolean }>
    >(`/api/projects/${projectId}/environments/${environmentId}/env-vars`)
      .then((vars) => {
        const missing = vars
          .filter((v) => !v.hasValue && !v.isAutoGenerated)
          .map((v) => ({ service: v.service, key: v.key, value: "" }));
        if (missing.length > 0) setEnvVars(missing);
      })
      .catch(() => {});
  }, [projectId, environmentId]);

  const updateConfig = (patch: Partial<HeizenConfig>) =>
    setConfig((c) => ({ ...c, ...patch }));

  const verifyAws = async () => {
    setVerifyResult(null);
    setVerifyError(null);
    try {
      await api(`/api/projects/${projectId}/environments/${environmentId}`, {
        method: "PATCH",
        body: JSON.stringify({ awsAccountId, awsRoleArn, region: config.region }),
      });
      const res = await api<{ ok: boolean; message: string }>(
        `/api/projects/${projectId}/environments/${environmentId}/aws/verify`,
        { method: "POST" },
      );
      setVerifyResult(res.message);
    } catch (err) {
      setVerifyError(
        err instanceof Error
          ? err.message
          : "Connection failed. Check role ARN and trust policy.",
      );
    }
  };

  const deploy = async () => {
    if (!awsRoleArn.trim()) {
      setDeployError("IAM Role ARN is required.");
      setStep(2);
      return;
    }
    if (!config.region.trim()) {
      setDeployError("Region is required.");
      setStep(1);
      return;
    }

    setDeploying(true);
    setDeployError(null);

    try {
      await api(`/api/projects/${projectId}/environments/${environmentId}`, {
        method: "PATCH",
        body: JSON.stringify({
          awsAccountId,
          awsRoleArn,
          region: config.region,
          domain: config.domain,
          heizenConfig: config,
        }),
      });

      if (envVars.length > 0) {
        await api(
          `/api/projects/${projectId}/environments/${environmentId}/env-vars/bulk`,
          { method: "PUT", body: JSON.stringify({ vars: envVars }) },
        );
      }

      const deployment = await api<{ id: string }>(
        `/api/projects/${projectId}/environments/${environmentId}/deployments`,
        { method: "POST", body: JSON.stringify({}) },
      );
      onDeploy(deployment.id);
    } catch (err) {
      setDeployError(
        err instanceof Error ? err.message : "Deployment failed. Check your configuration.",
      );
    } finally {
      setDeploying(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4">
      <Card className="max-h-[90vh] w-full max-w-2xl overflow-y-auto border-zinc-800 bg-zinc-900 p-5">
        <div className="mb-6 flex items-center justify-between">
          <h2 className="text-base font-semibold">
            Deploy to {envType} — Step {step}/4
          </h2>
          <button
            onClick={onClose}
            className="rounded-md p-1 text-muted-foreground transition-colors hover:bg-zinc-800 hover:text-white"
          >
            <X size={16} />
          </button>
        </div>

        {step === 1 && (
          <div className="space-y-4">
            <div>
              <Label>Region</Label>
              <Input
                value={config.region}
                onChange={(e) => updateConfig({ region: e.target.value })}
                className="mt-1.5"
              />
            </div>
            <div>
              <Label>Domain</Label>
              <Input
                value={config.domain ?? ""}
                onChange={(e) => updateConfig({ domain: e.target.value })}
                placeholder="app.example.com"
                className="mt-1.5"
              />
            </div>
            <div>
              <Label>NAT Gateway</Label>
              <select
                className="mt-1.5 flex h-8 w-full rounded-md border border-zinc-800 bg-zinc-950 px-3 text-sm"
                value={config.networking.nat}
                onChange={(e) =>
                  updateConfig({
                    networking: {
                      ...config.networking,
                      nat: e.target.value as HeizenConfig["networking"]["nat"],
                    },
                  })
                }
              >
                <option value="none">None ($0)</option>
                <option value="single">Single ($35)</option>
                <option value="dual">Dual HA ($70)</option>
              </select>
            </div>
            <CostEstimator config={config} />
            <Button size="sm" onClick={() => setStep(2)} className="w-full">
              Next: AWS Access
            </Button>
          </div>
        )}

        {step === 2 && (
          <div className="space-y-4">
            <div>
              <Label>AWS Account ID</Label>
              <Input
                value={awsAccountId}
                onChange={(e) => setAwsAccountId(e.target.value)}
                className="mt-1.5"
              />
            </div>
            <div>
              <Label>IAM Role ARN</Label>
              <Input
                value={awsRoleArn}
                onChange={(e) => setAwsRoleArn(e.target.value)}
                className="mt-1.5"
              />
            </div>
            <details className="text-sm text-muted-foreground">
              <summary className="cursor-pointer hover:text-foreground">
                How to create the IAM role
              </summary>
              <p className="mt-2 leading-relaxed">
                Create an IAM role in your AWS account that trusts the Heizen platform account
                with an external ID equal to your environment ID. Grant it AdministratorAccess
                or scoped permissions for ECS, RDS, ElastiCache, S3, ALB, and IAM.
              </p>
            </details>
            <Button size="sm" onClick={verifyAws} variant="outline">
              Test connection
            </Button>
            {verifyResult && <p className="text-sm text-green-500">{verifyResult}</p>}
            {verifyError && <p className="text-sm text-red-400">{verifyError}</p>}
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={() => setStep(1)}>
                Back
              </Button>
              <Button size="sm" onClick={() => setStep(3)} className="flex-1">
                Next: Environment variables
              </Button>
            </div>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Provide values for secrets detected from .env.example files.
            </p>
            {envVars.map((v, i) => (
              <div key={i} className="grid grid-cols-3 gap-2">
                <Input value={v.service} readOnly />
                <Input value={v.key} readOnly />
                <Input
                  type="password"
                  value={v.value}
                  onChange={(e) => {
                    const next = [...envVars];
                    next[i] = { ...v, value: e.target.value };
                    setEnvVars(next);
                  }}
                />
              </div>
            ))}
            <Button
              size="sm"
              variant="outline"
              onClick={() =>
                setEnvVars([...envVars, { service: "shared", key: "", value: "" }])
              }
            >
              Add variable
            </Button>
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={() => setStep(2)}>
                Back
              </Button>
              <Button size="sm" onClick={() => setStep(4)} className="flex-1">
                Next: Review
              </Button>
            </div>
          </div>
        )}

        {step === 4 && (
          <div className="space-y-4">
            <div className="space-y-1 rounded-md border border-zinc-800 bg-zinc-950 p-4 text-sm">
              <p>Region: {config.region}</p>
              <p>Domain: {config.domain || "None"}</p>
              <p>Services: {config.services.map((s) => s.name).join(", ")}</p>
              <p>Database: {config.database.engine}</p>
              <p>Cache: {config.cache.engine}</p>
            </div>
            <CostEstimator config={config} />
            <Separator />
            <div className="flex gap-2">
              <Button size="sm" variant="outline" onClick={() => setStep(3)}>
                Back
              </Button>
              <Button size="sm" onClick={deploy} disabled={deploying} className="flex-1">
                {deploying ? "Deploying..." : `Deploy to ${envType}`}
              </Button>
            </div>
            {deployError && (
              <p className="rounded-md bg-red-500/10 px-3 py-2 text-sm text-red-400">
                {deployError}
              </p>
            )}
          </div>
        )}
      </Card>
    </div>
  );
}
