"use client";

import { useEffect, useState } from "react";
import { Trash2, Plus } from "lucide-react";
import { Button, Card, Input, Label } from "@/components/ui";
import { api } from "@/lib/api";

interface EnvVar {
  id: string;
  service: string;
  key: string;
  hasValue: boolean;
  isAutoGenerated: boolean;
}

export function EnvVarTable({
  projectId,
  envId,
}: {
  projectId: string;
  envId: string;
}) {
  const [vars, setVars] = useState<EnvVar[]>([]);
  const [newVar, setNewVar] = useState({ service: "shared", key: "", value: "" });
  const [loading, setLoading] = useState(true);

  const load = async () => {
    const data = await api<EnvVar[]>(
      `/api/projects/${projectId}/environments/${envId}/env-vars`,
    );
    setVars(data);
    setLoading(false);
  };

  useEffect(() => {
    load();
  }, [projectId, envId]);

  const add = async () => {
    if (!newVar.key || !newVar.value) return;
    await api(`/api/projects/${projectId}/environments/${envId}/env-vars`, {
      method: "POST",
      body: JSON.stringify(newVar),
    });
    setNewVar({ service: "shared", key: "", value: "" });
    load();
  };

  const remove = async (varId: string) => {
    await api(
      `/api/projects/${projectId}/environments/${envId}/env-vars/${varId}`,
      { method: "DELETE" },
    );
    load();
  };

  if (loading) return <p className="text-[var(--muted)]">Loading...</p>;

  return (
    <Card>
      <h2 className="mb-4 text-lg font-semibold">Environment Variables</h2>
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-[var(--border)] text-left text-[var(--muted)]">
            <th className="pb-2">Service</th>
            <th className="pb-2">Key</th>
            <th className="pb-2">Value</th>
            <th className="pb-2"></th>
          </tr>
        </thead>
        <tbody>
          {vars.map((v) => (
            <tr key={v.id} className="border-b border-[var(--border)]/50">
              <td className="py-2">{v.service}</td>
              <td className="py-2">{v.key}</td>
              <td className="py-2 font-mono text-[var(--muted)]">
                {v.isAutoGenerated
                  ? "(auto-generated)"
                  : v.hasValue
                    ? "********"
                    : "(missing)"}
              </td>
              <td className="py-2 text-right">
                {!v.isAutoGenerated && (
                  <button
                    onClick={() => remove(v.id)}
                    className="text-[var(--error)] hover:opacity-80"
                  >
                    <Trash2 size={14} />
                  </button>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-4 grid grid-cols-4 gap-2">
        <Input
          placeholder="Service"
          value={newVar.service}
          onChange={(e) => setNewVar({ ...newVar, service: e.target.value })}
        />
        <Input
          placeholder="KEY"
          value={newVar.key}
          onChange={(e) => setNewVar({ ...newVar, key: e.target.value })}
        />
        <Input
          type="password"
          placeholder="Value"
          value={newVar.value}
          onChange={(e) => setNewVar({ ...newVar, value: e.target.value })}
        />
        <Button onClick={add}>
          <Plus size={16} className="mr-1" /> Add
        </Button>
      </div>
    </Card>
  );
}
