"use client";

import { useEffect, useState } from "react";
import { Trash2, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { api } from "@/lib/api";

interface EnvVar {
  id: string;
  service: string;
  key: string;
  hasValue: boolean;
  isAutoGenerated: boolean;
}

export function EnvVarTable({
  projectId,
  envId,
}: {
  projectId: string;
  envId: string;
}) {
  const [vars, setVars] = useState<EnvVar[]>([]);
  const [newVar, setNewVar] = useState({ service: "shared", key: "", value: "" });
  const [loading, setLoading] = useState(true);

  const load = async () => {
    const data = await api<EnvVar[]>(
      `/api/projects/${projectId}/environments/${envId}/env-vars`,
    );
    setVars(data);
    setLoading(false);
  };

  useEffect(() => {
    load();
  }, [projectId, envId]);

  const add = async () => {
    if (!newVar.key || !newVar.value) return;
    await api(`/api/projects/${projectId}/environments/${envId}/env-vars`, {
      method: "POST",
      body: JSON.stringify(newVar),
    });
    setNewVar({ service: "shared", key: "", value: "" });
    load();
  };

  const remove = async (varId: string) => {
    await api(
      `/api/projects/${projectId}/environments/${envId}/env-vars/${varId}`,
      { method: "DELETE" },
    );
    load();
  };

  if (loading) {
    return (
      <div className="space-y-2">
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-10 w-full" />
        <Skeleton className="h-10 w-full" />
      </div>
    );
  }

  return (
    <Card className="border-border bg-card p-4">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-border text-left text-muted-foreground">
            <th className="pb-2 font-medium">Service</th>
            <th className="pb-2 font-medium">Key</th>
            <th className="pb-2 font-medium">Value</th>
            <th className="pb-2" />
          </tr>
        </thead>
        <tbody>
          {vars.map((v) => (
            <tr key={v.id} className="border-b border-border/50">
              <td className="py-2">{v.service}</td>
              <td className="py-2 font-mono text-xs">{v.key}</td>
              <td className="py-2 font-mono text-xs text-muted-foreground">
                {v.isAutoGenerated
                  ? "(auto-generated)"
                  : v.hasValue
                    ? "********"
                    : "(missing)"}
              </td>
              <td className="py-2 text-right">
                {!v.isAutoGenerated && (
                  <button
                    onClick={() => remove(v.id)}
                    className="rounded-md p-1 text-destructive transition-colors hover:bg-muted"
                  >
                    <Trash2 size={14} />
                  </button>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mt-4 grid grid-cols-4 gap-2">
        <Input
          placeholder="Service"
          value={newVar.service}
          onChange={(e) => setNewVar({ ...newVar, service: e.target.value })}
        />
        <Input
          placeholder="KEY"
          value={newVar.key}
          onChange={(e) => setNewVar({ ...newVar, key: e.target.value })}
        />
        <Input
          type="password"
          placeholder="Value"
          value={newVar.value}
          onChange={(e) => setNewVar({ ...newVar, value: e.target.value })}
        />
        <Button size="sm" onClick={add}>
          <Plus size={14} className="mr-1" />
          Add
        </Button>
      </div>
    </Card>
  );
}
