-- AlterEnum
ALTER TYPE "IncidentSource" ADD VALUE 'LOGS';

-- AlterTable
ALTER TABLE "Incident" ADD COLUMN "occurrences" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
